### ISSUE TITLE
Consider adding plugin-source-opening support

### ISSUE THREAD

**Issue by TamaMcGlinn** [felipec/vim-sanegx#1]
When I am looking at my installed plugins in vimrc, some of the lines match a regex determined by the plugin manager in use, e.g. `Plug 'felipec/vim-sanegx'` - and I wanted a quick way to open the github page corresponding to the plugin.

I've added this to my ~/vimrc/ftplugin/vim.vim but I feel this fits really well inside of sane-gx.

```
function! OpenGithub() abort
  let l:line = getline('.')
  if l:line =~ "^Plug '"
    let url = substitute(substitute(l:line, "^Plug '", 'https://github.com/', ''), "'$", '', '')
    call GXBrowse(l:url)
  else
    call GXBrowse(expand('<cWORD>'))
  endif
endfunction

nnoremap <silent><buffer> gx :call OpenGithub()<CR>
```

Support for other plugin managers will be trivial to add. Since it is inside of ftplugins, it is not going to affect performance for non-vim buffers, and for vim buffers I think this is well worth those precious microseconds.

What do you think?

**Comment by felipec** [comment]
The whole point of sanegx is to be simple and no-nonsense, so I'm against adding any unnecessary features.

That being said, I might not be against adding a user configuration to replace `expand('<cWORD>')` with a function of the user's choosing.

**Comment by TamaMcGlinn** [comment]
That's fair enough. I'm going the other way with my fork, so if anyone wants to add features of things that should open in a browser even though they're not really URLs, feel free to add them in [vim-sanergx](https://github.com/TamaMcGlinn/vim-sanergx).

**Comment by felipec** [comment]
@TamaMcGlinn I'm not sure how much value you get from a fork, there's really not much difference between what you wrote:

    nnoremap <silent><buffer> gx :call sanergx#OpenGithub()<CR>
    
And what I proposed:

    nnoremap <silent><buffer> gx :call sanergx#GXBrowse(sanergx#GetGithub())<CR>

I modified your `OpenGithub()` to return the URL instad of opening it directly, and it works just fine.

Then it's a very small step to make `sanergx#GetGithub()` configurable.

**Comment by TamaMcGlinn** [comment]
I find it easier to only have to add a single plugin line, rather than having one plugin dependent on another. But I like the idea of just returning the url, I'm going to use that, since I will probably be adding more `GetXUrl()` functions.

**Comment by felipec** [comment]
Sure, but my point is that you don't need a second plugin, you could have `OpenGithub()` in your `.vimrc` or somewhere, and simply configure `vim-sanegx` to use that.

**Comment by TamaMcGlinn** [comment]
Yes, that works just as well. But I am moving in the other direction, because it is easier to share a list of plugins with others, than source code whose dependencies are unclear. The startup performance is also better when using plugins; GetGithub is not loaded until it is activated.
