### ISSUE TITLE
Using sanegx with markdown files.

### ISSUE THREAD

**Issue by sammynilla** [felipec/vim-sanegx#2]
Hi there,
I was curiously looking into your project the other day when I ran into the `gx` issue that so many people seemed to have issues with. I was trying it out and while it works in most cases there happened to be a particular edge case that was causing me issues.

I went ahead and toyed with the plugin myself but came up with no real level of success.

If you use `gx` on a markdown link such as: `[link](https://www.github.com)` then it actually copies all the way back to the very first square bracket. This of course makes the call to `GXBrowse()` sometimes fail, and in my case, my terminal to also become completely unresponsive.

If you have any ideas at all I'd love to hear them, even if you don't have the time or interest in the upkeep of vim-sanegx.

**Comment by felipec** [comment]
The problem is that `<cWORD>` returns the entire current word, which is not what you want in your case.

But it shouldn't be hard to write a wrapper around the program you use to open URLs, for example:

```bash
#!/bin/bash
regex="(https?|ftp|file)://[a-zA-Z0-9\-\._~%!$&'*+,;=:@/?#]*"
[[ $1 =~ $regex ]] && xdg-open "$BASH_REMATCH"
```

You add that to your `$PATH` and then add this configuration to your `~.vimrc`:

```vim
let g:netrw_browsex_viewer='open-bad-url'
```

**Comment by sammynilla** [comment]
Sounds good! I'll give it a shot, and I appreciate your response. 😄
